_target_: src.models.text_alignment_model.TextAlignmentModel

eo_encoder:
  _target_: src.models.components.eo_encoders.geoclip.GeoClipCoordinateEncoder

text_encoder:
  _target_: src.models.components.text_encoders.clip_text_encoder.ClipTextEncoder
  hf_cache_dir: ${paths.huggingface_cache}

trainable_modules: [text_encoder.projector, loss_fn.temperature]

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

loss_fn:
  _target_: src.models.components.loss_fns.clip_loss.ClipLoss
  temperature: 0.07
