# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# falls back to "." if PROJECT_ROOT is not set

root_dir: ${oc.env:PROJECT_ROOT,.}

# path to data directory
data_dir: ${SHARED_ROOT}/data/

# path to data splits directory
splits: ${paths.data_dir}/splits/

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${SHARED_ROOT}/${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}

# huggingface cache directory
# can be overridden via HF_HOME environment variable
huggingface_cache: ${oc.env:HF_HOME,${SHARED_CACHE}/huggingface}