# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# falls back to "." if PROJECT_ROOT is not set

root_dir: ${oc.env:PROJECT_ROOT,./}

# path to data directory
data_dir: ${oc.env:DATA_DIR,oc.env:SHARED_ROOT/data/,${paths.root_dir}/data/}

# path to data splits directory
splits: ${paths.data_dir}/splits/

# path to logging directory
log_dir: ${oc.env:SHARED_ROOT}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/local.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}

# huggingface cache directory
# can be overridden via HF_HOME environment variable
huggingface_cache: ${oc.env:HF_HOME,oc.env:SHARED_CACHE/huggingface}
